# Generated by Django 5.1.7 on 2025-03-30 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='casevideo',
            name='case',
        ),
        migrations.RemoveField(
            model_name='case',
            name='statement',
        ),
        migrations.AddField(
            model_name='case',
            name='category',
            field=models.CharField(default='Other', max_length=100),
        ),
        migrations.AddField(
            model_name='case',
            name='subcategories',
            field=models.JSONField(default=list),
        ),
        migrations.DeleteModel(
            name='CaseDocument',
        ),
        migrations.DeleteModel(
            name='CaseVideo',
        ),
    ]
