# Generated by Django 5.1.7 on 2025-06-26 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_emailotp_remove_customuser_mobile_number'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OTP',
        ),
    ]
