# Generated by Django 5.1.7 on 2025-07-15 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_delete_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_lawyer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_victim',
            field=models.BooleanField(default=False),
        ),
    ]
